/*
 * collection-library-server-API
 * API for collection-library-server
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pl.wsb.collection.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * ModifyRole
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-06-15T21:16:59.062Z")
public class ModifyRole   {
  @JsonProperty("user_id")
  private Integer userId = null;

  @JsonProperty("role_id")
  private Integer roleId = null;

  /**
   * Gets or Sets function
   */
  public enum FunctionEnum {
    ADD("add"),
    
    DELETE("delete");

    private String value;

    FunctionEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FunctionEnum fromValue(String text) {
      for (FunctionEnum b : FunctionEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("function")
  private FunctionEnum function = null;

  public ModifyRole userId(Integer userId) {
    this.userId = userId;
    return this;
  }

  /**
   * User&#39;s id
   * @return userId
   **/
  @JsonProperty("user_id")
  @ApiModelProperty(required = true, value = "User's id")
  @NotNull
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public ModifyRole roleId(Integer roleId) {
    this.roleId = roleId;
    return this;
  }

  /**
   * Role&#39;s id
   * @return roleId
   **/
  @JsonProperty("role_id")
  @ApiModelProperty(required = true, value = "Role's id")
  @NotNull
  public Integer getRoleId() {
    return roleId;
  }

  public void setRoleId(Integer roleId) {
    this.roleId = roleId;
  }

  public ModifyRole function(FunctionEnum function) {
    this.function = function;
    return this;
  }

  /**
   * Get function
   * @return function
   **/
  @JsonProperty("function")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public FunctionEnum getFunction() {
    return function;
  }

  public void setFunction(FunctionEnum function) {
    this.function = function;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyRole modifyRole = (ModifyRole) o;
    return Objects.equals(this.userId, modifyRole.userId) &&
        Objects.equals(this.roleId, modifyRole.roleId) &&
        Objects.equals(this.function, modifyRole.function);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, roleId, function);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyRole {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

